/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* ADC_IRQ */
#define ADC_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define ADC_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define ADC_IRQ__INTC_NUMBER 138u
#define ADC_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define ADC_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define ADC_IRQ_INTC_NUMBER 138u

/* adc_int */
#define adc_int__INTC_CORTEXM4_ASSIGNED 1
#define adc_int__INTC_CORTEXM4_PRIORITY 7u
#define adc_int__INTC_NUMBER 122u
#define adc_int_INTC_CORTEXM4_ASSIGNED 1
#define adc_int_INTC_CORTEXM4_PRIORITY 7u
#define adc_int_INTC_NUMBER 122u

/* Bouton_ISR */
#define Bouton_ISR__INTC_CORTEXM4_ASSIGNED 1
#define Bouton_ISR__INTC_CORTEXM4_PRIORITY 7u
#define Bouton_ISR__INTC_NUMBER 0u
#define Bouton_ISR_INTC_CORTEXM4_ASSIGNED 1
#define Bouton_ISR_INTC_CORTEXM4_PRIORITY 7u
#define Bouton_ISR_INTC_NUMBER 0u

/* I2C_1_SCB_IRQ */
#define I2C_1_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define I2C_1_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define I2C_1_SCB_IRQ__INTC_NUMBER 43u
#define I2C_1_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define I2C_1_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define I2C_1_SCB_IRQ_INTC_NUMBER 43u

/* UART_1_SCB_IRQ */
#define UART_1_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define UART_1_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define UART_1_SCB_IRQ__INTC_NUMBER 42u
#define UART_1_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define UART_1_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define UART_1_SCB_IRQ_INTC_NUMBER 42u

/* CY_EINK_SPIM_SCB_IRQ */
#define CY_EINK_SPIM_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define CY_EINK_SPIM_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define CY_EINK_SPIM_SCB_IRQ__INTC_NUMBER 47u
#define CY_EINK_SPIM_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define CY_EINK_SPIM_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define CY_EINK_SPIM_SCB_IRQ_INTC_NUMBER 47u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
